spring:
  application:
    name: opc-collector

opc:
  host: ip
  domain: ""
  user: Administrator
  password: "password"
  prog-id: "PROGID"
  clsId: "clsId"
  group-name: "spring-opc-group"
  update-rate: 1000

collector:
  fixed-delay-ms: 5000
  files:
    - D:/opc-app/points/OPC_CONF四线.csv

output:
  csv-file: D:/opc-app/output/collect-result.csv

mqtt:
  broker: tcp://ip:1883
  username: username
  password: password
  dataTopic: /opcServer/sendData